#!/bin/sh
MACHINE=$(basename $0)
case "$1" in
	create)
		docker-machine create \
			--driver virtualbox \
			--virtualbox-cpu-count "2" \
			--virtualbox-memory "4096" \
			--virtualbox-share-folder "$HOME/work/minidock:work" \
			$MACHINE
	;;

	eval)
		eval $(docker-machine env $MACHINE)
		export DOCKER_TLS_VERIFY
		export DOCKER_HOST
		export DOCKER_CERT_PATH
		export DOCKER_MACHINE_NAME
	;;

	*)
		docker-machine status $MACHINE >/dev/null 2>&1 || $MACHINE create
		docker-machine status $MACHINE | grep Running >/dev/null 2>&1 || docker-machine start $MACHINE
		docker-machine "${@}" $MACHINE
	;;
esac
